// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfqzjnlnkesaqrrmdytz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcXpqbmxua2VzYXFycm1keXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NDAzNTgsImV4cCI6MjA1MzAxNjM1OH0.W-TahQLcjzrB_2QRJjLgd1IDXZOHftKcdaWwKnrmv-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);